### ISSUE TITLE
batch size support?

### ISSUE THREAD

**Issue by vasiliyb** [SebastiaanKlippert/go-soda#2]
Folks, Next(uint) seems to not behave as expected.

When scraping full datasets, and setting Next(100) seems to return 1000 rows unlike the example in the docs: `resp, err := ogr.Next(2000)`

It seems that the default result count is `1000` https://github.com/SebastiaanKlippert/go-soda/blob/master/soda.go#L211 so shouldnt the offset be `1000?

**Comment by SebastiaanKlippert** [comment]
Hi, 

Can you please share some sample code where this happens?
If have tried this in my existing tests and they seem to pass, so I am not sure why you are seeing different results.

Maybe newer datasets behave differently, but this is what I did:

```go
package main

import (
	"encoding/json"
	"log"

	"github.com/SebastiaanKlippert/go-soda"
)

func main() {

	gr := soda.NewGetRequest("https://data.ct.gov/resource/y6p2-px98", "")
	gr.Format = "json"
	gr.Query.AddOrder("farm_name", soda.DirAsc)

	ogr, err := soda.NewOffsetGetRequest(gr)
	if err != nil {
		log.Fatal(err)
	}

	for i := 0; i < 1; i++ {

		ogr.Add(1)
		go func() {
			defer ogr.Done()

			for {
				resp, err := ogr.Next(100)
				if err == soda.ErrDone {
					break
				}
				if err != nil {
					log.Fatal(err)
				}

				var results []Business
				err = json.NewDecoder(resp.Body).Decode(&results)
				resp.Body.Close()
				if err != nil {
					log.Fatal(err)
				}

				log.Println(len(results))
			}
		}()

	}
	ogr.Wait()

}

type Business struct {
	FarmName string `json:"farm_name"`
}
```

This prints 
100
100
[...]
100
94

Increasing the number of goroutines in the for loop does not change this and changing the value in the `Next()` call changes the output as expected.

> It seems that the default result count is 1000 https://github.com/SebastiaanKlippert/go-soda/blob/master/soda.go#L211 so shouldnt the offset be `1000?

Offset should start at 0 or you would not get the first 1000 records. Limit should be 1000.

**Comment by vasiliyb** [comment]
Thank you !!!  
The dataset I am trying to query is:
```
gr := soda.NewGetRequest("https://data.cityofnewyork.us/resource/bnx9-e6tj", c.options.Token)
gr.Format = "json"
gr.Query.AddOrder("document_id", soda.DirAsc)
```

Maybe its the `document_id` thats throwing it off?

**Comment by SebastiaanKlippert** [comment]
That also works here.

```go
package main

import (
	"encoding/json"
	"log"

	"github.com/SebastiaanKlippert/go-soda"
)

func main() {

	gr := soda.NewGetRequest("https://data.cityofnewyork.us/resource/bnx9-e6tj", "")
	gr.Format = "json"
	gr.Query.AddOrder("document_id", soda.DirAsc)

	ogr, err := soda.NewOffsetGetRequest(gr)
	if err != nil {
		log.Fatal(err)
	}

	for i := 0; i < 1; i++ {

		ogr.Add(1)
		go func() {
			defer ogr.Done()

			for {
				resp, err := ogr.Next(100)
				if err == soda.ErrDone {
					break
				}
				if err != nil {
					log.Fatal(err)
				}

				var results []X
				err = json.NewDecoder(resp.Body).Decode(&results)
				resp.Body.Close()
				if err != nil {
					log.Fatal(err)
				}

				log.Println(len(results))
			}
		}()

	}
	ogr.Wait()

}

type X struct {
	DocId string `json:"document_id"`
}
```
Output is 
```
2019/05/01 11:47:22 100
2019/05/01 11:47:22 100
2019/05/01 11:47:23 100
2019/05/01 11:47:23 100
2019/05/01 11:47:24 100
[...]
```

Can you run this code on your machine to see what the output is?

**Comment by vasiliyb** [comment]
I've confirmed the issue, the way i was instantiating an instance of the client was not being passed in correct options!   Thus it was defaulting to 1K :) .  Thank you Thank you Thank you!  Closing.
